hpe-storage/scod

- docs/docker_volume_plugins/hpe_3par_primera_storage/index.md
- docs/flexvolume_driver/3par_primera_provider/index.md
- docs/flexvolume_driver/container_provider/index.md
- docs/flexvolume_driver/hpe_3par_primera_installer/index.md
- mkdocs.yml
> 3par/Primera Ansible installer documentation migration to scod

- docs/index.md
> Moving GitHub badge

- docs/container_storage_provider/hpe_nimble_storage/index.md
- docs/csi_driver/deployment.md
- docs/csi_driver/using.md
> Secret changes to reflect what the Helm chart and Operator deploys

- docs/csi_driver/index.md
> version fix for 5.1.x

- docs/csi_driver/index.md
> add blogs to 1.1.1

- docs/csi_driver/using.md
> storageclass fixes

- docs/csi_driver/index.md
- docs/partners/redhat_openshift/index.md
> request from eng/qa + typo

- docs/learn/persistent_storage/index.md
> fixed storageclass

- docs/legal/support/index.md
- docs/partners/redhat_openshift/index.md
> Support Matrix updated

- docs/learn/introduction_to_containers/index.md
- mkdocs.yml
> HPE learning path

- docs/learn/introduction_to_containers/index.md
> Fix broken links

- docs/container_storage_provider/hpe_nimble_storage/index.md
- docs/csi_driver/using.md
> Add verbiage for volume mutator

- docs/container_storage_provider/hpe_nimble_storage/index.md
- docs/csi_driver/deployment.md
- docs/csi_driver/diagnostics.md
- docs/csi_driver/index.md
- docs/csi_driver/using.md
- add verbiage for `hpenodeinfos` diags
- iSCSI CHAP blurbs
- Mutator clarifications for Nimble
> more towards 1.3.0

- docs/container_storage_provider/hpe_3par_primera/index.md
> minor updates to support matrix

- docs/csi_driver/archive.md
- docs/csi_driver/deployment.md
- docs/csi_driver/index.md
- docs/partners/index.md
- docs/partners/redhat_openshift/index.md
> CSI 1.3.0 updates + fixes

- docs/container_storage_provider/hpe_3par_primera/index.md
> removed reference to resizer sidecar

- docs/csi_driver/deployment.md
> CSI 1.3.0 fixes and clarifcations on what we support

- docs/container_storage_provider/hpe_3par_primera/index.md
- docs/csi_driver/index.md
> Updated support for k8s 1.19

- docs/csi_driver/using.md
> Enbling snapshots to make more sense

- docs/csi_driver/using.md
> snapshot controller for real

- docs/container_storage_provider/hpe_3par_primera/index.md
- docs/csi_driver/index.md
> update to supported k8s version

- docs/csi_driver/deployment.md
- docs/learn/persistent_storage/index.md
> fixed error in command

- docs/index.md
> KubeCon2020 promo

- docs/index.md
- docs/learn/csi_workshop/index.md
- docs/partners/index.md
- docs/partners/kasten/index.md
> Post KubeCon and link fixings

- docs/csi_driver/deployment.md
- docs/partners/index.md
- docs/partners/mirantis/index.md
- mkdocs.yml
> MKE support

- docs/learn/csi_primitives/index.md
- mkdocs.yml
> Introduction to CSI Primitives

- docs/csi_driver/monitor.md
- docs/csi_driver/using.md
> Removed beta/tech preview caveats

- docs/container_storage_provider/hpe_nimble_storage/index.md
- docs/csi_driver/diagnostics.md
- docs/csi_driver/using.md
> First pass on Volume and Snapshot Groups

- docs/learn/video_gallery/index.md
> added Peer Persistence Video to Video Gallery

- docs/csi_driver/deployment.md
- docs/csi_driver/index.md
> Namespace for advanced install

- docs/csi_driver/using.md
> fix provisioner reference

- docs/csi_driver/index.md
> Add protocol limitation

- docs/container_storage_provider/hpe_nimble_storage/index.md
> Formatting issue

- docs/csi_driver/using.md
> Clarify mutator behavior

- docs/partners/redhat_openshift/index.md
> operator deployment name fix

- docs/csi_driver/index.md
> Clarification for limitation

- docs/learn/persistent_storage/index.md
- docs/learn/persistent_storage/yaml/my-pvc.yaml
- docs/learn/persistent_storage/yaml/my-wordpress-pvc.yaml
- docs/learn/persistent_storage/yaml/nginx-stateless-deployment.yaml
- docs/learn/persistent_storage/yaml/nimble-secret.yaml
- docs/learn/persistent_storage/yaml/nimble-storageclass.yaml
- docs/learn/persistent_storage/yaml/primera-secret.yaml
- docs/learn/persistent_storage/yaml/primera-storageclass.yaml
- docs/learn/persistent_storage/yaml/wordpress-mariadb-pvc.yaml
> many updates to the lab guide and hosting yaml

- docs/learn/persistent_storage/index.md
> further updates to lab guide

- docs/container_storage_provider/hpe_nimble_storage/index.md
> Peer Persistence is not supported with Nimble

- docs/csi_driver/index.md
> Ephemeral node limitation

- docs/csi_driver/using.md
> Add fstype parameter clarification

- docs/partners/redhat_openshift/index.md
> updated OpenShift docs

- docs/index.md
> HPE Alletra admonition

- docs/csi_driver/deployment.md
> Missed update

- docs/csi_driver/deployment.md
> Operator update

- docs/csi_driver/using.md
> Doc bug and clarifications

- docs/csi_driver/using.md
Addresses comments made in #107 
> Snapshot CRD and controller clarifications

- docs/csi_driver/deployment.md
> NFS note for air-gapped installs

- docs/ezmeral_container_platform/install.md
> Ezmeral updates

- docs/learn/persistent_storage/index.md
> updates to lab guide

- docs/learn/persistent_storage/index.md
> added optional configuration in lab guide

- docs/learn/persistent_storage/index.md
> fix for certificate error

- docs/legal/notices/index.md
- mkdocs.yml
> Adding notices

- docs/learn/video_gallery/index.md
> Adding and fixing videos

- docs/container_storage_provider/hpe_alletra_9000/index.md
- docs/csi_driver/deployment.md
- docs/csi_driver/install_legacy.md
> v2.1.0 items

- docs/partners/redhat_openshift/index.md
Signed-off-by: Michael Mattsson [michael.mattsson@gmail.com](mailto:michael.mattsson@gmail.com)
> OCP upgrade blurb

- requirements.txt
> v2.1.1-buildfix

- docs/csi_driver/using.md
> Clarified RWX for volumeMode: Block

- docs/partners/vmware/index.md
> vSphere CSI driver support matrix

- docs/css/hpedev.css
- docs/partners/redhat_openshift/index.md
- mkdocs.yml
- requirements.txt
> fsMode typo

- .github/workflows/main.yml
> Switching to newer action

- docs/csi_driver/using.md
> NFS limitation update

- docs/css/hpedev.css
> Improve list layouts

- README.md
- docs/csi_driver/deployment.md
- docs/csi_driver/diagnostics.md
- docs/csi_driver/install_legacy.md
- docs/csi_driver/metrics.md
- docs/csi_driver/monitor.md
- docs/csi_driver/using.md
- docs/docker_volume_plugins/hpe_cloud_volumes/index.md
- docs/docker_volume_plugins/hpe_nimble_storage/index.md
- docs/ezmeral_container_platform/install.md
- docs/flexvolume_driver/container_provider/index.md
- docs/flexvolume_driver/hpe_3par_primera_installer/index.md
- docs/learn/persistent_storage/index.md
- docs/legal/contributing/index.md
- docs/legal/license/index.md
- docs/legal/notices/index.md
- docs/partners/commvault/index.md
- docs/partners/kasten/index.md
- docs/partners/mirantis/index.md
- docs/partners/redhat_openshift/index.md
- docs/partners/suse_rancher/index.md
- docs/partners/vmware/index.md
> Fixed code blocks to match latest MkDocs

- docs/container_storage_provider/hpe_alletra_9000/index.md
> grammar fix

- docs/partners/redhat_openshift/index.md
> uninstall added to OpenShift

- docs/container_storage_provider/hpe_alletra_9000/index.md
> rcg clarification

- docs/css/hpedev.css
Somewhere something broke that made table cells run forever.
> Fix table wraps

- docs/csi_driver/using.md
> RWX Block note

- docs/csi_driver/deployment.md
- docs/csi_driver/index.md
- docs/csi_driver/using.md
- docs/legal/notices/index.md
- mkdocs.yml
> Clarify Volume Groups, Happy New Year and some lint

- docs/partners/redhat_openshift/index.md
> OpenShift field tested updates.

- docs/partners/redhat_openshift/index.md
Jumped the gun on the previous PR. Grammar has been fixed. 
> OpenShift field tested updates, part 2.

- docs/partners/redhat_openshift/index.md
Passed CSI e2e tests with Primera 4.5.7.
> Changed to All CSPs

- docs/csi_driver/examples/standalone_nfs/base/configmap.yaml
- docs/csi_driver/examples/standalone_nfs/base/deployment.yaml
- docs/csi_driver/examples/standalone_nfs/base/environment.properties
- docs/csi_driver/examples/standalone_nfs/base/kustomization.yaml
- docs/csi_driver/examples/standalone_nfs/base/pvc.yaml
- docs/csi_driver/examples/standalone_nfs/base/service.yaml
- docs/csi_driver/examples/standalone_nfs/base/values.yaml
- docs/csi_driver/examples/standalone_nfs/overlays/example/environment.properties
- docs/csi_driver/examples/standalone_nfs/overlays/example/kustomization.yaml
- docs/csi_driver/standalone_nfs.md
For testing, replace the git clone URL with this branch.
> First pass standalone NFS

- docs/csi_driver/index.md
- docs/legal/support/index.md
- Merge when the operator is live.
- Updated support statement requested by Nimble team
> 2.3.0 final

- docs/partners/redhat_openshift/index.md
A customer discovered an issue with XFS while using NFS backed volumes. This is the suggested workaround.
> ext4 notice

- docs/partners/vmware/index.md
- docs/partners/vmware/legacy.md
- Moved old unmaintained deployment guide to legacy
- Updated dead URLs
- More verbiage around considerations and platforms
> vSphere updates

- docs/container_storage_provider/hpe_alletra_6000/index.md
- Requested by an internal customer
> Static example

- docs/filex_csi_driver/deployment.md
- docs/filex_csi_driver/examples/deployment/hpegreenlakefilecsidriver-v1.0.0-beta-sample.yaml
- docs/filex_csi_driver/index.md
- docs/filex_csi_driver/using.md
- docs/partners/redhat_openshift/examples/scc/hpe-filex-csi-scc.yaml
- mkdocs.yml
> HPE GreenLake for File Storage beta docs

- docs/csi_driver/deployment.md
- docs/csi_driver/operations.md
- docs/csi_driver/partners/hpe_morpheus/install.md
- docs/csi_driver/using.md
- mkdocs.yml
- Some typos
- Added initial Morpheus page
- Added section on image updates
- Clarified NFS server resource parameters
> MKS and image manipulation
